#!/bin/bash


function is_osx {
    if [ "$(uname -s)" == "Darwin" ]; then
        return 0  # zero means success because this is a unix function
    else
        return 1
    fi
}


# This Script Location -- http://stackoverflow.com/questions/59895/
MY_PROFILE_HOME="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"


# Helpful Git Scripts -- https://git-scm.com/book/en/v1/Git-Basics-Tips-and-Tricks
source "${MY_PROFILE_HOME}/git-completion.sh"
source "${MY_PROFILE_HOME}/git-prompt.sh"


# Edit Prompt -- http://www.tldp.org/HOWTO/Bash-Prompt-HOWTO/x329.html
ESC="\[\033[0m\]"
BLACK="\[\033[0;30m\]"
RED="\[\033[0;31m\]"
GREEN="\[\033[0;32m\]"
YELLOW="\[\033[0;33m\]"
BLUE="\[\033[0;34m\]"
MAGENTA="\[\033[0;35m\]"
CYAN="\[\033[0;36m\]"

PS1="${YELLOW}\$? \! \t \u@\h:\W${GREEN}\$(__git_ps1)${YELLOW}\$${ESC} "


# Aliases
if $(is_osx); then
    alias ls="ls -G -lh"
else
    alias ls="ls --color -lh"
fi

alias grep="grep -E"
alias reup="source ${MY_PROFILE_HOME}/my_bash_env"
alias vi="vim '+syntax on' '+set number'"


# Paths
if $(is_osx); then
    export JAVA_HOME="$(/usr/libexec/java_home)"
else
    export JAVA_HOME="$(${MY_PROFILE_HOME}/java_home)"
fi

export APPS="${HOME}/Applications"

export BASE_PATH="${BASE_PATH:-${PATH}}"  # prevent path from growing larger every time this file is sourced
export PATH="${BASE_PATH}"
